#ifndef IOTCLIENT_RJLSHY5B

#define IOTCLIENT_RJLSHY5B

enum CLIENT_OPERATION {
  CLIENT_OPERATION_QUERY_SENSOR_LIST = 1,
  CLIENT_OPERATION_SUBSCRIBE_ALL_SENSORS = 2,
  CLIENT_OPERATION_SUBSCRIBE_TO_SENSOR_NONRELIABLE = 3,
  CLIENT_OPERATION_SUBSCRIBE_TO_SENSOR_RELIABLE = 4,
  CLIENT_OPERATION_UNSUBSCRIBE = 5,
  CLIENT_OPERATION_SHUTDOWN = 6
};



#endif /* end of include guard: IOTCLIENT_RJLSHY5B */
