enable_testing()
find_package(Check REQUIRED)
include_directories(${CHECK_INCLUDE_DIRS})
set(LIBS ${LIBS} ${CHECK_LIBRARIES} pubsub iotclient_testlib iotserver_testlib)
include_directories(. ../src/)
add_executable(check_sensor_parser check_sensor_parser.c)
add_executable(check_bson_parser check_bson_parser.c)
add_executable(check_clients check_clients.c) 
add_executable(check_transport check_transport.c)
target_link_libraries(check_sensor_parser ${LIBS})
target_link_libraries(check_bson_parser ${LIBS})
target_link_libraries(check_clients ${LIBS})
target_link_libraries(check_transport ${LIBS})
add_test(check_sensor_parser ${CMAKE_CURRENT_BINARY_DIR}/check_sensor_parser)
add_test(check_bson_parser ${CMAKE_CURRENT_BINARY_DIR}/check_bson_parser)
add_test(check_clients ${CMAKE_CURRENT_BINARY_DIR}/check_clients)
add_test(check_transport ${CMAKE_CURRENT_BINARY_DIR}/check_transport)
